#!/bin/bash
# Wallust Cache Warming Script
# Generated by Synapse (CLI Operator) based on Architect's Blueprint.

WP_DIR="$HOME/Wallpapers"
CACHE_DIR="$HOME/.cache/wallust"

# 1. PREP
if [ ! -d "$WP_DIR" ]; then
    echo "Error: $WP_DIR does not exist."
    exit 1
fi

notify-send -i terminal "Synapse" "Building Wallust Cache..."

# 2. CLEAN
# Removing cache to ensure a fresh, consistent build as per blueprint.
echo "Cleaning old cache..."
rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR"

# 3. EXECUTION LOOP
IMAGES=("$WP_DIR"/*.jpg "$WP_DIR"/*.png "$WP_DIR"/*.jpeg)
TOTAL=${#IMAGES[@]}
COUNT=0

echo "Rebuilding cache for $TOTAL images..."

for IMG in "${IMAGES[@]}"; do
    [ -e "$IMG" ] || continue # Handle case with no matches
    ((COUNT++))
    PERCENT=$((COUNT * 100 / TOTAL))
    
    # Progress bar calculation
    BAR_SIZE=40
    FILLED=$((PERCENT * BAR_SIZE / 100))
    UNFILLED=$((BAR_SIZE - FILLED))
    BAR=$(printf "%${FILLED}s" | tr ' ' '#')$(printf "%${UNFILLED}s" | tr ' ' '-')
    
    # Print progress line
    printf "[%s] %d%% (%d/%d)" "$BAR" "$PERCENT" "$COUNT" "$TOTAL"
    
    # Run wallust in generation-only mode
    # -q: quiet
    # -s: skip terminal sequences (prevent flickering)
    wallust run --skip-templates --skip-sequences -q "$IMG"
done

# 4. FINISH
echo -e "

Cache Rebuild Complete."
notify-send -i terminal "Synapse" "Cache Rebuild Complete."
